Claimable feature
chainlabs-dlt/cryptocookies pull request #7
Opened 2023-07-12 12:45 UTC by emduc

feature for claimable amounts in front ed

2023-07-13 21:35 UTC, AlSchlo commented on frontend/src/utils/Staking.ts
> +    stakedToken: string;
Why is this necessary?
You can fetch the string of the token with just the contract address.

2023-07-13 21:37 UTC, AlSchlo commented on frontend/src/utils/Staking.ts
> +    constructor(stakedToken: string, stakingContract: string, userState: any, globalState: any, account: string | undefined) {
We should only need a contract address to build a Staking object. If we bring the userState & other from the external environment, we break encapsulation completely.

2023-07-13 21:37 UTC, AlSchlo commented on frontend/src/utils/Staking.ts
> +    updateGlobalIndex(index: Decimal,  revenue: Decimal): Decimal {
I'm not familiar with the visibilities of TS, but be sure this is private.

2023-07-13 21:39 UTC, AlSchlo commented on frontend/src/utils/Staking.ts
> +        this.approveHook(this.stakingContract, amount);
It's not really a hook, you could change the name. Also, you could check if it is needed and use an infinite approval. Or even better, you could leverage offchain signatures using the ERC20Permit interface!

2023-07-13 21:40 UTC, AlSchlo commented on frontend/src/utils/Staking.ts
> +
Formatting is weird here, check your formatter's parameters?

2023-07-13 21:42 UTC, AlSchlo commented on frontend/src/utils/Staking.ts
> +            // TODO, what if is has been more than 1 period??
The whole buffer should be distributed. This should be clear in CkiDistr code I believe.

2023-07-13 21:44 UTC, AlSchlo commented on frontend/src/utils/Staking.ts
> +    claimable(blockTimeStamp: Decimal) {
NOTE: A lot of this code will be duplicated when we will code "claimable" for the locking front-end integration. So it's fine for now but we'll need a plan to factorize this code (probably including it in CkiDistr.ts).

2023-07-13 21:46 UTC, AlSchlo commented on frontend/src/utils/Contracts.ts
> + ** ERC-20 Related functions ***
NOTE: Keep in mind that these functions return React "hooks". Basically reactive values that can be injected into React components. If you want to call a smart contract function once only, you should NOT use hooks. Also, usefull hooks should be integrated directly within XX.ts class code for better usability.

2023-07-13 21:51 UTC, AlSchlo commented on frontend/src/utils/Contracts.ts
> +export function Approve(tokenAddress: string) {
Same here, I would research more what the advantages are of using UseDApp useContractFunction() hook instead of a simple etherjs call to approve a transaction. Maybe we can leverage the transaction receipt, but in either way it does not seem to be used here?

2023-07-13 21:53 UTC, AlSchlo requested changes
Nice start! Needs more polishing but I really like the shape it's taking. Try to think: "How will the front-end WANT to use this code", to adopt the best design decisions.

2023-07-13 21:55 UTC, AlSchlo commented on frontend/src/utils/Staking.ts
> +    updateGlobalIndex(index: Decimal,  revenue: Decimal): Decimal {
More generally, try to seperate the external API vs the internal API. For each contract. we want to identify its external API first.

2023-09-19 15:05 UTC, emduc commented
work included in #13  (merged)

2023-09-19 15:05 UTC, closed without merging